apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: microcks-import-task
spec:
  params:
    - name: specificationFilesList
      type: string
      description: "<specificationFile1[:primary],specificationFile2[:primary]>: Comma separated list of API specs to import with flag telling if it's a primary artifact. Example: ''specs/my-openapi.yaml:true,specs/my-postmancollection.json:false''"
      default: "'./valid-openapi.yaml:true'"
    - name: microcksURL
      type: string
      description: "Microcks instance API endpoint"
      default: "https://microcks-microcks.apps.cluster-fp5qq.fp5qq.sandbox1387.opentlc.com/"	
    - name: keycloakSecret
      type: string
      description: "Keycloak Realm Service Account ClientSecret"
      default: "ab54d329-e435-41ae-a900-ec6b3fe15c54"
    - name: keycloakClientId
      type: string
      description: "Keycloak Service Account keycloakClientId"
      default: "microcks-serviceaccount"
  workspaces:
  - name: data
  steps:
    - name: microcks-test
      image: quay.io/microcks/microcks-cli:0.5.0
      workingDir: $(workspaces.data.path)
      command:
        - /usr/bin/bash
      args:
        - '-c'
        - >-
          microcks-cli import "./valid-openapi.yaml:true" \
            --microcksURL="https://microcks-microcks.apps.cluster-fp5qq.fp5qq.sandbox1387.opentlc.com/api/" \
            --keycloakClientId="microcks-serviceaccount" --keycloakClientSecret="ab54d329-e435-41ae-a900-ec6b3fe15c54" \
            --insecure
      securityContext:
        runAsUser: 0
